const express=require('express');
const db=require('../config/db');
const {requireAdmin}=require('../middleware/auth');
const {syncDevices,testConnection,config}=require('../services/acsService');
const {audit}=require('../services/auditService');
const router=express.Router();
const localReturn=value=>String(value||'').startsWith('/acs')?String(value):'/acs';

async function options(){const [sites]=await db.query(`SELECT id,code,name FROM sites WHERE is_active=1 ORDER BY code`);const [clusters]=await db.query(`SELECT cl.id,cl.name,s.code site_code FROM clusters cl JOIN sites s ON s.id=cl.site_id WHERE cl.status<>'inactive' ORDER BY s.code,cl.name`);return {sites,clusters};}
router.get('/',async(req,res,next)=>{try{
  const q=String(req.query.q||'').trim(),status=['online','offline','unknown'].includes(req.query.status)?req.query.status:'',signal=['normal','warning','critical','unknown'].includes(req.query.signal)?req.query.signal:'',site=String(req.query.site||'').trim(),mapping=['linked','unlinked'].includes(req.query.mapping)?req.query.mapping:'';
  let where=['1=1'];const params=[];if(q){where.push(`(d.serial_number LIKE ? OR d.device_id LIKE ? OR d.pppoe_username LIKE ? OR d.ssid LIKE ? OR c.name LIKE ? OR c.customer_code LIKE ?)`);const like=`%${q}%`;params.push(like,like,like,like,like,like);}if(status){where.push('d.online_status=?');params.push(status);}if(signal){where.push('d.signal_status=?');params.push(signal);}if(site){where.push('s.code=?');params.push(site);}if(mapping==='linked')where.push('l.id IS NOT NULL');if(mapping==='unlinked')where.push('l.id IS NULL');
  const [devices]=await db.execute(`SELECT d.*,l.id link_id,l.match_method,l.is_locked,c.id customer_id,c.customer_code,c.name customer_name,c.customer_status,c.network_status,s.code site_code,cl.name cluster_name,p.name package_name FROM acs_devices d LEFT JOIN customer_ont_links l ON l.acs_device_id=d.id LEFT JOIN customers c ON c.id=l.customer_id LEFT JOIN sites s ON s.id=c.site_id LEFT JOIN clusters cl ON cl.id=c.cluster_id LEFT JOIN packages p ON p.id=c.package_id WHERE ${where.join(' AND ')} ORDER BY FIELD(d.online_status,'offline','unknown','online'),FIELD(d.signal_status,'critical','warning','unknown','normal'),c.name,d.serial_number LIMIT 750`,params);
  const [[summary]]=await db.query(`SELECT COUNT(*) total,SUM(online_status='online') online,SUM(online_status='offline') offline,SUM(signal_status='warning') warning,SUM(signal_status='critical') critical,SUM(NOT EXISTS(SELECT 1 FROM customer_ont_links l WHERE l.acs_device_id=acs_devices.id)) unlinked FROM acs_devices`);
  const [[lastSync]]=await db.query(`SELECT * FROM acs_sync_logs ORDER BY id DESC LIMIT 1`);res.render('acs/index',{title:'Monitoring ONT',devices,summary:summary||{},lastSync,filters:{q,status,signal,site,mapping},...(await options()),acsConfigured:!!config().baseUrl});
}catch(err){next(err);}});

router.get('/map',async(req,res,next)=>{try{
  const [rows]=await db.query(`SELECT COALESCE(s.code,'BELUM DIPETAKAN') site_code,COALESCE(cl.name,d.odp_name,'ODP BELUM DIISI') odp_name,d.id,d.serial_number,d.online_status,d.signal_status,d.rx_power,c.id customer_id,c.customer_code,c.name customer_name FROM acs_devices d LEFT JOIN customer_ont_links l ON l.acs_device_id=d.id LEFT JOIN customers c ON c.id=l.customer_id LEFT JOIN sites s ON s.id=c.site_id LEFT JOIN clusters cl ON cl.id=c.cluster_id ORDER BY site_code,odp_name,c.name,d.serial_number`);
  const siteMap=new Map();for(const row of rows){if(!siteMap.has(row.site_code))siteMap.set(row.site_code,{name:row.site_code,odps:new Map()});const siteNode=siteMap.get(row.site_code);if(!siteNode.odps.has(row.odp_name))siteNode.odps.set(row.odp_name,{name:row.odp_name,devices:[]});siteNode.odps.get(row.odp_name).devices.push(row);}
  const sites=[...siteMap.values()].map(site=>({...site,odps:[...site.odps.values()].map(odp=>{const offline=odp.devices.filter(d=>d.online_status==='offline').length,critical=odp.devices.filter(d=>d.signal_status==='critical').length;return {...odp,offline,critical,status:offline>0?'offline':critical>0?'critical':odp.devices.some(d=>d.signal_status==='warning')?'warning':'online'};})}));
  const [[lastSync]]=await db.query(`SELECT * FROM acs_sync_logs ORDER BY id DESC LIMIT 1`);res.render('acs/map',{title:'Network Map ONT',sites,lastSync});
}catch(err){next(err);}});

router.get('/reconcile',async(req,res,next)=>{try{
  const [devices]=await db.query(`SELECT d.* FROM acs_devices d LEFT JOIN customer_ont_links l ON l.acs_device_id=d.id WHERE l.id IS NULL ORDER BY d.last_inform DESC LIMIT 500`);
  const [customers]=await db.query(`SELECT c.id,c.customer_code,c.name,c.pppoe_username,s.code site_code,cl.name cluster_name FROM customers c JOIN sites s ON s.id=c.site_id LEFT JOIN clusters cl ON cl.id=c.cluster_id LEFT JOIN customer_ont_links l ON l.customer_id=c.id WHERE c.archived_at IS NULL AND c.customer_status='active' AND l.id IS NULL ORDER BY s.code,cl.name,c.name LIMIT 1000`);
  res.render('acs/reconcile',{title:'Rekonsiliasi ONT',devices,customers});
}catch(err){next(err);}});

router.post('/sync',requireAdmin,async(req,res)=>{try{const result=await syncDevices();req.session.flash={type:result.status==='success'?'success':'warning',message:result.status==='success'?`Sinkronisasi selesai: ${result.devices} ONT, ${result.linked} mapping otomatis baru.`:'Sinkronisasi lain sedang berjalan.'};}catch(err){req.session.flash={type:'danger',message:`Sinkronisasi ACS gagal: ${err.message}`};}res.redirect(localReturn(req.body.return_to));});
router.post('/test',requireAdmin,async(req,res)=>{try{const result=await testConnection();req.session.flash={type:'success',message:`GenieACS terhubung (${result.latencyMs} ms).`};}catch(err){req.session.flash={type:'danger',message:`Koneksi gagal: ${err.message}`};}res.redirect('/acs');});
router.post('/link',requireAdmin,async(req,res)=>{const customerId=Number(req.body.customer_id),deviceId=Number(req.body.acs_device_id);try{if(!customerId||!deviceId)throw new Error('Pelanggan dan ONT wajib dipilih.');await db.execute(`INSERT INTO customer_ont_links(customer_id,acs_device_id,match_method,is_locked,linked_by) VALUES(?,?,'manual',1,?)`,[customerId,deviceId,req.session.user.id]);await audit({userId:req.session.user.id,action:'link_ont',entityType:'acs_device',entityId:deviceId,description:`Mapping manual ONT ke pelanggan #${customerId}`,ip:req.ip});req.session.flash={type:'success',message:'ONT berhasil dihubungkan ke pelanggan dan mapping dikunci.'};}catch(err){req.session.flash={type:'danger',message:`Mapping gagal: ${err.code==='ER_DUP_ENTRY'?'Pelanggan atau ONT sudah memiliki mapping.':err.message}`};}res.redirect('/acs/reconcile');});
router.post('/devices/:id/path',requireAdmin,async(req,res)=>{const allowed=value=>String(value||'').trim().slice(0,120)||null;await db.execute(`UPDATE acs_devices SET olt_name=?,pon_port=?,splitter_name=?,odp_name=? WHERE id=?`,[allowed(req.body.olt_name),allowed(req.body.pon_port),allowed(req.body.splitter_name),allowed(req.body.odp_name),req.params.id]);await audit({userId:req.session.user.id,action:'update_ont_path',entityType:'acs_device',entityId:req.params.id,description:'Memperbarui metadata jalur OLT/PON/Splitter/ODP',ip:req.ip});req.session.flash={type:'success',message:'Metadata jalur ONT diperbarui.'};res.redirect('/acs');});
module.exports=router;
