const express = require('express');
const db = require('../config/db');
const { createReportPdf, rupiah } = require('../services/reportPdf');

const router = express.Router();
const money = (value) => Math.round(Number(value || 0));
const validDate = (value) => /^\d{4}-\d{2}-\d{2}$/.test(String(value || ''));
const dateOr = (value, fallback) => validDate(value) ? String(value) : fallback;
const siteBlock = (code) => { const value = String(code || '').trim().toUpperCase(); if (value === 'KBG' || value.includes('KUBANG')) return 'kbg'; if (value === 'KRW' || value === 'CLM') return 'krwclm'; return 'other'; };
const personKey = (value) => { const name = String(value || '').trim().toLowerCase(); if (name.includes('edwin')) return 'edwin'; if (name.includes('jon') || name.includes('roni')) return 'jon'; if (name.includes('bopung') || name.includes('eko')) return 'bopung'; if (name.includes('ali')) return 'mang ali'; return name; };

async function loadClosing(start, end) {
  const [[period]] = await db.execute('SELECT * FROM closing_periods WHERE period_start=? AND period_end=? LIMIT 1', [start, end]);
  const closing = period || { status: 'DRAFT', manual_revenue: 0, manual_expense: 0, manual_carry: 0, manual_salary_agung: 500000, manual_salary_padilah: 1000000, notes: '' };
  const [payments] = await db.execute(`SELECT DATE(p.paid_at) paid_date,c.name customer_name,c.customer_code,s.code site_code,p.amount,p.method FROM payments p JOIN invoices i ON i.id=p.invoice_id JOIN customers c ON c.id=i.customer_id JOIN sites s ON s.id=c.site_id WHERE p.status='confirmed' AND DATE(p.paid_at) BETWEEN ? AND ? ORDER BY p.paid_at DESC,p.id DESC`, [start, end]);
  const [expenses] = await db.execute(`SELECT ct.transaction_date,ct.name,cc.name category,COALESCE(s.code,'-') site_code,ct.amount,ct.notes FROM cash_transactions ct JOIN cash_categories cc ON cc.id=ct.category_id LEFT JOIN sites s ON s.id=ct.site_id WHERE cc.type='expense' AND COALESCE(ct.approval_status,'APPROVED')='APPROVED' AND ct.transaction_date BETWEEN ? AND ? ORDER BY ct.transaction_date DESC,ct.id DESC`, [start, end]);
  const [heldCash] = await db.execute(`SELECT DATE(p.paid_at) paid_date,c.name customer_name,s.code site_code,p.amount,COALESCE(u.name,'Belum diketahui') holder_name FROM payments p JOIN invoices i ON i.id=p.invoice_id JOIN customers c ON c.id=i.customer_id JOIN sites s ON s.id=c.site_id LEFT JOIN users u ON u.id=COALESCE(p.collector_user_id,p.received_by) WHERE p.status='confirmed' AND p.method='cash' AND p.settlement_status='held_by_staff' AND DATE(p.paid_at) BETWEEN ? AND ? ORDER BY p.paid_at DESC,p.id DESC`, [start, end]);
  const [routerAssets] = await db.execute(`SELECT customer_name,site_code,owner_name,units,status,active_from,active_until,notes FROM closing_router_assets WHERE active_from<=? AND (active_until IS NULL OR active_until>=?) AND status IN ('ACTIVE','BROKEN','REPLACED') ORDER BY site_code,customer_name`, [end, start]);
  const [adjustments] = period ? await db.execute('SELECT * FROM closing_adjustments WHERE closing_id=? ORDER BY id', [period.id]) : [[]];
  const blocks = { krwclm: { label: 'KRW + CLM', revenue: 0, expense: 0 }, kbg: { label: 'KBG', revenue: 0, expense: 0 }, other: { label: 'Lokasi belum dipetakan', revenue: 0, expense: 0, shares: [] } };
  payments.forEach((row) => { blocks[siteBlock(row.site_code)].revenue += money(row.amount); });
  expenses.forEach((row) => { blocks[siteBlock(row.site_code)].expense += money(row.amount); });
  blocks.krwclm.revenue += money(closing.manual_revenue); blocks.krwclm.expense += money(closing.manual_expense);
  Object.values(blocks).forEach((block) => { block.profit = block.revenue - block.expense; });
  blocks.krwclm.profit += money(closing.manual_carry);
  const heldBy = new Map(); heldCash.forEach((row) => { const key = personKey(row.holder_name); heldBy.set(key, (heldBy.get(key) || 0) + money(row.amount)); });
  const routerByOwner = new Map(); routerAssets.forEach((row) => { if (row.status === 'ACTIVE') { const key = personKey(row.owner_name); routerByOwner.set(key, (routerByOwner.get(key) || 0) + Math.max(0, Number(row.units || 0)) * 20000); } });
  const salaryTotal = money(closing.manual_salary_agung) + money(closing.manual_salary_padilah);
  const salaryByOwner = { edwin: salaryTotal * .50, jon: salaryTotal * .25, bopung: salaryTotal * .25 };
  const adjusted = (name, gross, includeSalary = false) => { const key = personKey(name); let value = gross + (routerByOwner.get(key) || 0) - (heldBy.get(key) || 0); if (includeSalary) value -= salaryByOwner[key] || 0; adjustments.filter((item) => personKey(item.recipient_name) === key).forEach((item) => { value += item.direction === 'DEDUCT' ? -money(item.amount) : money(item.amount); }); return money(value); };
  blocks.krwclm.shares = [{ name: 'Edwin', percent: 50, gross: money(blocks.krwclm.profit * .50), amount: adjusted('Edwin', blocks.krwclm.profit * .50, true) }, { name: 'Jon', percent: 25, gross: money(blocks.krwclm.profit * .25), amount: adjusted('Jon', blocks.krwclm.profit * .25, true) }, { name: 'Bopung', percent: 25, gross: money(blocks.krwclm.profit * .25), amount: adjusted('Bopung', blocks.krwclm.profit * .25, true) }];
  const pool = blocks.kbg.profit * .65;
  blocks.kbg.shares = [{ name: 'Edwin', percent: 41.418, gross: money(pool * .6372), amount: adjusted('Edwin', pool * .6372) }, { name: 'Jon', percent: 11.791, gross: money(pool * .1814), amount: adjusted('Jon', pool * .1814) }, { name: 'Bopung', percent: 11.791, gross: money(pool * .1814), amount: adjusted('Bopung', pool * .1814) }, { name: 'Mang Ali', percent: 35, gross: money(blocks.kbg.profit * .35), amount: adjusted('Mang Ali', blocks.kbg.profit * .35) }];
  return { closing, period, payments, expenses, heldCash, routerAssets, blocks, salaryTotal, salaryRows: [{ name: 'Agung', amount: money(closing.manual_salary_agung) }, { name: 'Padilah', amount: money(closing.manual_salary_padilah) }] };
}

function selectedPeriod(req) { const now = new Date(); return { start: dateOr(req.query.from || req.body?.from, new Date(now.getFullYear(), now.getMonth(), 1).toISOString().slice(0, 10)), end: dateOr(req.query.to || req.body?.to, new Date(now.getFullYear(), now.getMonth() + 1, 0).toISOString().slice(0, 10)) }; }

router.get('/', async (req, res, next) => { try { const { start, end } = selectedPeriod(req); if (start > end) return res.status(400).send('Periode tidak valid.'); const data = await loadClosing(start, end); res.render('closing/index', { title: 'Closing', pageTitle: 'Closing', pageSubtitle: `${start} s/d ${end}`, start, end, money, ...data }); } catch (err) { next(err); } });

router.post('/save', async (req, res, next) => { try { const { start, end } = selectedPeriod(req); if (start > end) return res.status(400).send('Periode tidak valid.'); const n = (v, fallback = 0) => Number.isFinite(Number(v)) ? Number(v) : fallback; const [[old]] = await db.execute('SELECT id,status FROM closing_periods WHERE period_start=? AND period_end=? LIMIT 1', [start, end]); if (old?.status === 'LOCKED') return res.status(409).send('Closing sudah dikunci.'); const values = [Math.max(0,n(req.body.manual_revenue)), Math.max(0,n(req.body.manual_expense)), n(req.body.manual_carry), Math.max(0,n(req.body.manual_salary_agung,500000)), Math.max(0,n(req.body.manual_salary_padilah,1000000)), String(req.body.notes || '').slice(0,2000)]; if (old) await db.execute('UPDATE closing_periods SET manual_revenue=?,manual_expense=?,manual_carry=?,manual_salary_agung=?,manual_salary_padilah=?,notes=? WHERE id=?', [...values, old.id]); else await db.execute('INSERT INTO closing_periods(period_start,period_end,closing_date,manual_revenue,manual_expense,manual_carry,manual_salary_agung,manual_salary_padilah,notes,created_by) VALUES(?,?,CURDATE(),?,?,?,?,?,?,?)', [start,end,...values,req.session.user.id]); req.session.flash={type:'success',message:'Penyesuaian Closing tersimpan.'}; res.redirect(`/closing?from=${start}&to=${end}`); } catch (err) { next(err); } });

router.post('/router-assets', async (req, res, next) => { try { const { start, end }=selectedPeriod(req); const name=String(req.body.customer_name||'').trim().slice(0,180); const owner=String(req.body.owner_name||'').trim().slice(0,100); const date=validDate(req.body.active_from)?req.body.active_from:''; const site=String(req.body.site_code||'CLM').trim().toUpperCase().slice(0,30); const units=Math.max(1,Math.min(100,Math.floor(Number(req.body.units||1)))); if(!name||!owner||!date)return res.status(400).send('Nama pelanggan, pemilik, dan tanggal mulai wajib diisi.'); await db.execute('INSERT INTO closing_router_assets(customer_name,site_code,owner_name,units,active_from,status,notes,created_by) VALUES(?,?,?,?,?,?,?,?)',[name,site,owner,units,date,'ACTIVE',String(req.body.notes||'').slice(0,500),req.session.user.id]); req.session.flash={type:'success',message:'Data INVEST ROUTER tersimpan.'}; res.redirect(`/closing?from=${start}&to=${end}`); } catch(err){next(err);} });

router.post('/lock', async (req, res, next) => { const { start, end }=selectedPeriod(req); let conn; try { if(start>end)return res.status(400).send('Periode tidak valid.'); conn=await db.getConnection(); await conn.beginTransaction(); const [rows]=await conn.execute('SELECT * FROM closing_periods WHERE period_start=? AND period_end=? FOR UPDATE',[start,end]); if(!rows.length){await conn.rollback();return res.status(400).send('Simpan penyesuaian dahulu sebelum mengunci.');} if(rows[0].status==='LOCKED'){await conn.rollback();return res.redirect(`/closing?from=${start}&to=${end}`);} await conn.execute("UPDATE closing_periods SET status='LOCKED',locked_by=?,locked_at=NOW() WHERE id=?",[req.session.user.id,rows[0].id]); await conn.execute('INSERT INTO closing_audit_logs(closing_id,action,details_json,actor_id) VALUES(?,?,?,?)',[rows[0].id,'LOCK',JSON.stringify({start,end}),req.session.user.id]); await conn.commit(); req.session.flash={type:'success',message:'Closing berhasil dikunci.'}; res.redirect(`/closing?from=${start}&to=${end}`); } catch(err){if(conn)await conn.rollback();next(err);} finally{if(conn)conn.release();} });

router.get('/pdf', async (req,res,next)=>{ try { const {start,end}=selectedPeriod(req); if(start>end)return res.status(400).send('Periode tidak valid.'); const data=await loadClosing(start,end); const rows=[]; Object.values(data.blocks).forEach((b)=>rows.push({type:'RINGKASAN',lokasi:b.label,penerima:'',detail:`Pendapatan ${rupiah(b.revenue)} · Pengeluaran ${rupiah(b.expense)}`,nominal:rupiah(b.profit)})); Object.values(data.blocks).forEach((b)=> (b.shares||[]).forEach((s)=>rows.push({type:'PEMBAGIAN',lokasi:b.label,penerima:s.name,detail:`${s.percent}% · Kotor ${rupiah(s.gross)}`,nominal:rupiah(s.amount)}))); rows.push(...data.payments.map((r)=>({type:'PEMBAYARAN',lokasi:r.site_code,penerima:r.customer_name,detail:`${r.paid_date} · ${r.method||'-'}`,nominal:rupiah(r.amount)}))); rows.push(...data.expenses.map((r)=>({type:'PENGELUARAN',lokasi:r.site_code,penerima:r.name,detail:`${r.transaction_date} · ${r.category}`,nominal:rupiah(r.amount)}))); rows.push(...data.heldCash.map((r)=>({type:'CASH BELUM SETOR',lokasi:r.site_code,penerima:r.holder_name,detail:`${r.paid_date} · ${r.customer_name}`,nominal:`- ${rupiah(r.amount)}`}))); createReportPdf(res,{title:'Closing INKAMNET',subtitle:`Periode transaksi ${start} s/d ${end}`,filename:`closing-${start}-${end}.pdf`,summaryItems:Object.values(data.blocks).map((b)=>({label:`${b.label} · Laba Bersih`,value:rupiah(b.profit),color:b.profit>=0?'#18A979':'#FF433E'})),columns:[{label:'Jenis',key:'type',width:1.1},{label:'Lokasi',key:'lokasi',width:1},{label:'Penerima/Keterangan',key:'penerima',width:2},{label:'Detail',key:'detail',width:2.4},{label:'Nominal',key:'nominal',width:1.2,align:'right'}],rows}); }catch(err){next(err);} });

module.exports = router;
